### ISSUE TITLE
Crash during the calculation of the distance between buildings

### ISSUE THREAD

**Issue by VakankGrang** [orbisgis/MApUCE_tools#26]
During the execution of the "complete geoprocessing chain" for the urban area of Dijon
I obtained a crash for the commune 21231 during the part  "Compute the distance between buildings"

org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: Chunk 2554 no longer exists [1.4.192/9]"; SQL statement:
CREATE TABLE DATA_WORK.DIST (PK integer PRIMARY KEY, MIN_DIST double precision,  MEAN_DIST double precision, MAX_DIST double precision, STD_DIST double precision, PK_USR integer)AS SELECT a.PK, MIN(ST_DISTANCE(a.THE_GEOM, b.THE_GEOM)) AS MIN_DIST, AVG(ST_DISTANCE(a.THE_GEOM, b.THE_GEOM)) AS MEAN_DIST, MAX(ST_DISTANCE(a.THE_GEOM, b.THE_GEOM)) AS MAX_DIST, STDDEV_POP(ST_DISTANCE(a.THE_GEOM, b.THE_GEOM)) AS STD_DIST,a.PK_USR FROM BUILDINGS_MAPUCE a, BUILDINGS_MAPUCE b WHERE a.PK<>b.PK AND a.PK_USR=b.PK_USR GROUP BY a.PK_USR, a.PK [50000-192]

The error is only partly reproducible since another execution on the same machine causes the same crash (but with another Chunk number) and the execution on another machine worked perfectly (but lead to the same kind of crash for other communes).
It could be a problem due to strong allocation of memory in the case where many buildings are located in one commune (or many in one USR). Do we really need the indicator "distance between buildings" or could it be calculated more easily (e.g. not all buildings with all buildings)?

Best regards,
Robert

**Comment by ebocher** [comment]
It's due to a memory overhead. Try to use the last OrbisGIS version and run ./orbisgis_safemode.sh. It will be able to adapt the available memory on your lattop.
By the way, there is another on Dijon at commune 84114. The input building data are inconsistency. Some buildings have a null PK so the process crashes on : 
org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON DATA_WORK.USR_TO_CENTER(PK_USR)"; SQL statement:
CREATE TABLE DATA_WORK.USR_TO_CENTER (PK_USR integer primary key, DIST_TO_CENTER double precision) AS SELECT a.PK as PK_USR, ST_DISTANCE(ST_CENTROID(a.THE_GEOM), ST_CENTROID(b.THE_GEOM)) AS DIST_TO_CENTER FROM USR_MAPUCE a, COMMUNE_MAPUCE b [23505-192]
I will work on it ASAP.

**Comment by VakankGrang** [comment]
Thanks for your help,

The geoprocessing chain for Dijon has been executed with success, although
my newly installed ORBISGIS and MAPUCE_Tools indicates still
Bnd-LastModified: 20 septembre 2016 12:18:59 GMT+01:00
Is this correct?
I also don't understand your remark on commune 84114. 
It is not part of the Dijon agglomeration !?

Best regards,
Robert

**Comment by ebocher** [comment]
Sorry I think about Avignon.... but a data input pb ;-(
About the Bnd-LastModified you are at the good place ;-).

**Comment by gpetit** [comment]
@VakankGrang Erwan just indicates that there is many errors in the entry data ... that we can not resolved (not our job) : 
- sometimes, different city have the same INSEE Code (which is mandatory in theory),
- sometimes, buildings are not associated to an USR,
- sometimes, a city is present many times, 
- ...

As a consequence, the script can crash when you're faced with these data

**Comment by VakankGrang** [comment]
Thanks for the detailed answers.
However, I don't understand what will be the strategy for dealing with the wrong input data.
Complete abandonment of these communes? 
I think we should correct the input data at each time we face such a crash (or is this not possible?)

Best regards,
Robert

**Comment by ebocher** [comment]
Correct the data at each bug will be hard task. Don't forget this job was done during 18 months...
I prefer to find a workaround ;-)

**Comment by ebocher** [comment]
Fixed here #28 .
But ... found a new bug on 

nique index or primary key violation: "PRIMARY KEY ON PUBLIC.FINAL_USR_INDICATORS(PK_USR)"; SQL statement:
INSERT INTO FINAL_USR_INDICATORS (SELECT \* FROM USR_INDICATORS); [

**Comment by VakankGrang** [comment]
The problem with the crash during the calculation of the distance between buildings is not solved!
Indeed, with the newest version of ORBISGIS and the Toolbox (1.0.3) there are still crashes for communes with more than ~ 20000 inhabitants. I tested it on both Windows and Linux. 

The typical error message is:
org.h2.jdbc.JdbcSQLException: General error: "java.lang.IllegalStateException: Chunk 18623 no longer exists [1.4.192/9]"; SQL statement:
CREATE TABLE DATA_WORK.DIST (PK integer PRIMARY KEY, MIN_DIST double precision,  MEAN_DIST double precision, MAX_DIST double precision, STD_DIST double precision, PK_USR integer)AS SELECT a.PK, MIN(ST_DISTANCE(a.THE_GEOM, b.THE_GEOM)) AS MIN_DIST, AVG(ST_DISTANCE(a.THE_GEOM, b.THE_GEOM)) AS MEAN_DIST, MAX(ST_DISTANCE(a.THE_GEOM, b.THE_GEOM)) AS MAX_DIST, STDDEV_POP(ST_DISTANCE(a.THE_GEOM, b.THE_GEOM)) AS STD_DIST,a.PK_USR FROM BUILDINGS_MAPUCE a, BUILDINGS_MAPUCE b WHERE a.PK<>b.PK AND a.PK_USR=b.PK_USR GROUP BY a.PK_USR, a.PK [50000-192]

The number of the chunk "that no longer exists" varies for each execution, the error message is thus not fully reproducible. I observed the memory allocation during the execution and found that there has only been about 10% of the memory used by java (both Windows and Linux).

Best regards,
Robert

**Comment by nicolas-f** [comment]
Hi,

This is a H2 database error. [https://groups.google.com/forum/#!searchin/h2-database/Chunk$20no$20longer$20exists|sort:relevance](https://groups.google.com/forum/#!searchin/h2-database/Chunk$20no$20longer$20exists|sort:relevance)
The database is corrupted. This can happen when the application is killed during a process. You have to remove the file database.mv.db in the workspace and re-run all queries.

**Comment by VakankGrang** [comment]
Hello,

I tested removing the file database.mv.db (and even removing all orbisgis directories) and it ends up with the same error message.

I also consider that the discussion on the website you referenced does not necessarily indicate that such an error occurs when the database is corrupted. Instead it seems to be a problem related to deletion of parts of the workspace after 45 s! Just look at the statement of Thomas Müller Graf on 
https://groups.google.com/forum/#!searchin/h2-database/Chunk$20no$20longer$20exists|sort:relevance/h2-database/DkhygS5hi5w/GOhZGtXOingJ

I analysed the time between the beginning of the computations and the crash and it is indeed close to 45 s. So this could be the reason.

IanP suggested to set
"db connection to use mv_store=false as a mitigation"

However,
Since I am not an expert on this type of programming I cannot judge whether this is the reason for the problems.

Best regards,
Robert

**Comment by VakankGrang** [comment]
Just an update,
If I set mv_store=false in the database "customisation" the problem seems to be solved. However, this kind of setting seems to lead to accumulation of very large files in the ORBISGIS working directory.
Best regards,
Robert

**Comment by ebocher** [comment]
The last H2 database version 1.4.193 seems to fix this issue.
